### ISSUE TITLE
How to use this code to implement zoom in/out features like your iOS app?

### ISSUE THREAD

**Issue by navigator117** [gongzhang/julia-set-playground#1]
How to use this code to implement zoom in/out features like your iOS app?
Not just generate a huge image, but part of it when zoom in, an with low level of details when zoom out?

**Comment by gongzhang** [comment]
You can adjust `center` and `window` property on `JuliaSet`:
- `window`: the scale of generated image (in math coordinate, small value == zoom in)
- `center`: where your image will focus on

![2017-07-06 9 13 27](https://user-images.githubusercontent.com/4470629/27891264-687c22a0-622b-11e7-9635-154ddc24d373.png)

Alternatively, you can also export a fractal as *encoded url* from the app, then decode it in playground:

```swift
code = "juliaset://?code=17F87FFF7FFF7FFF329A7CFF"
julia = JuliaSet.decodeURL(code)!

// you can observe these values now:
julia.const
julia.color
julia.center
julia.window
```

**Comment by navigator117** [comment]
Thanks! I have impelement it in Unity use shader code. And It works great!

**Comment by navigator117** [comment]
And another question, :), Is it possible to make It grow up like a nature plant? 1st show a main trunk, then add branches and leaves?

**Comment by gongzhang** [comment]
@navigator117 
I'll commit another playground project to demonstrate that :)

**Comment by navigator117** [comment]
That' will be great. And I'm awaiting it!

**Comment by gongzhang** [comment]
@navigator117 
A new repo for plant-like fractals:
<img width="300" alt="IFS Fractal" src="https://user-images.githubusercontent.com/4470629/28105680-14714004-6713-11e7-80cb-a9e241dad726.png">

I just committed the initial code. You can try it out :)
[/gongzhang/ifs-fractal-playground](https://github.com/gongzhang/ifs-fractal-playground)

**Comment by navigator117** [comment]
It's cool! Can you do the same thing on julia set or mandelbrot set ?

**Comment by gongzhang** [comment]
I'm afraid not 😟
